name: OWASP Dependency-Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout c贸digo
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Rodar Dependency-Check com chave NVD no workflow
        run: |
          mvn -f src/back/producao/sensor-fix/pom.xml clean org.owasp:dependency-check-maven:check \
            -Dformat=HTML \
            -DoutputDirectory=dependency-check-report \
            -Dnvd.api.key=b05af210-227a-490b-8374-d85d0bf43996

      - name: Upload relat贸rio OWASP como artifact
        uses: actions/upload-artifact@v4
        with:
          name: owasp-dependency-check-report
          path: dependency-check-report/**

      - name: Copiar relat贸rio local do servidor (se existir)
        run: |
          if [ -f src/back/producao/sensor-fix/target/dependency-check-report.html ]; then
            mkdir -p local-server-report
            cp src/back/producao/sensor-fix/target/dependency-check-report.html local-server-report/
          fi

      - name: Upload relat贸rio OWASP do servidor como artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: owasp-dependency-check-server
          path: local-server-report/**
