name: OWASP Dependency-Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout c贸digo
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Rodar Dependency-Check gerando relat贸rio em docs/
        run: |
          mvn -f src/back/producao/sensor-fix/pom.xml clean org.owasp:dependency-check-maven:check \
            -Dformat=HTML \
            -DoutputDirectory=docs/dependency-check-report

      - name: Commitar relat贸rio para docs/
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/dependency-check-report/dependency-check-report.html
          git commit -m "Atualiza relat贸rio OWASP Dependency-Check"
          git push
