name: OWASP Dependency-Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:  # permite rodar manualmente 

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Rodar Dependency-Check gerando relatório
        run: |
          mvn -f src/back/producao/sensor-fix/pom.xml clean org.owasp:dependency-check-maven:check \
            -Dformat=HTML \
            -DoutputDirectory=dependency-check-report

      - name: Upload relatório OWASP como artifact
        uses: actions/upload-artifact@v4
        with:
          name: owasp-dependency-check-report
          path: dependency-check-report/**
