name: OWASP Dependency-Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'sensor-fix'
          scanPath: 'src/back/producao/sensor-fix'

      - name: Upload relatório
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: '**/dependency-check-report.*'
